CREATE TABLE Pessoa(
Id INT NOT NULL AUTO_INCREMENT,
NomeRazao VARCHAR(255) NOT NULL,
	CONSTRAINT pk_Pessoa PRIMARY KEY(Id)
);

INSERT INTO Pessoa(NomeRazao)
VALUES
('FORNECEDOR 1'),
('FORNECEDOR 2'),
('FORNECEDOR 3'),
('FORNECEDOR 4');

SELECT * FROM Pessoa;